### ISSUE TITLE
First Attempt at reading Command Line Args

### ISSUE THREAD

**Issue by cpilkington78** [cpilkington78/ASCIITranslator#4]
Champ,

Please review code.  I cannot figure out why I can't set args [1] to the string variable userPath and then display it to the screen.  Not sure I'm reading the command line arguments correctly.  Hints please.

**Comment by cpilkington78** [comment]
Never mind, I forgot the {0} when I formatted the string!  It is working correctly now!  Lol!  I will continue working on this code.  I will get everything working first, and then work on the issue where it is procedural and not Object Oriented.

**Comment by cchampio** [comment]
Very good!
